# Generated by Django 5.0.6 on 2025-04-15 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='addition_details',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='users',
            name='social_media_links',
        ),
    ]
