# Generated by Django 5.0.6 on 2025-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Staff', 'Staff')], default='Customer', max_length=50, null=True),
        ),
    ]
