# Generated by Django 5.0.6 on 2025-05-30 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditriskassessment',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user_id_risk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditriskassessment',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_risk', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditriskassessment',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user_id_risk', to=settings.AUTH_USER_MODEL),
        ),
    ]
