# Generated by Django 5.0.6 on 2025-05-30 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0002_creditriskassessment_created_by_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_prices', models.JSONField()),
                ('exchange_rates', models.JSONField(blank=True, null=True)),
                ('interest_rates', models.JSONField(blank=True, null=True)),
                ('value_at_risk', models.FloatField(blank=True, null=True)),
                ('expected_shortfall', models.FloatField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_market_risks', to=settings.AUTH_USER_MODEL)),
                ('domain_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('updated_by_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_market_risks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
