# Generated by Django 5.0.6 on 2025-05-30 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0003_marketriskassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyWarningIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('SPENDING', 'Spending Pattern'), ('TRANSACTION', 'Transaction Pattern'), ('STOCK', 'Stock Movement'), ('LOAN', 'Loan Default Risk'), ('NEWS', 'News Sentiment')], max_length=20)),
                ('value', models.FloatField()),
                ('threshold', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ews_indicators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
