# Generated by Django 5.0.6 on 2025-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0004_earlywarningindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlywarningindicator',
            name='threshold',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='earlywarningindicator',
            name='value',
            field=models.JSONField(),
        ),
    ]
