# Generated by Django 5.0.6 on 2025-05-30 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0005_alter_earlywarningindicator_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gdp_growth', models.FloatField()),
                ('inflation', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('market_volatility', models.FloatField()),
                ('predicted_risk', models.IntegerField(choices=[(0, 'Low Risk'), (1, 'Medium Risk'), (2, 'High Risk')])),
                ('confidence_score', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
