# Generated by Django 5.0.6 on 2025-07-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0006_financialindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditriskassessment',
            name='ended_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditriskassessment',
            name='started_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlywarningindicator',
            name='ended_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlywarningindicator',
            name='started_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialindicator',
            name='ended_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialindicator',
            name='started_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketriskassessment',
            name='ended_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketriskassessment',
            name='started_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
