# Generated by Django 5.0.6 on 2025-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0007_creditriskassessment_ended_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditriskassessment',
            name='loan_duration_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
