# Generated by Django 5.0.6 on 2025-07-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0008_creditriskassessment_loan_duration_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialindicator',
            name='created_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_financial_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialindicator',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_risk_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialindicator',
            name='updated_by_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_financial_risks', to=settings.AUTH_USER_MODEL),
        ),
    ]
