# Generated by Django 5.0.6 on 2025-07-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CreditRisk', '0009_financialindicator_created_by_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialindicator',
            name='user',
        ),
    ]
