# Generated by Django 5.0.6 on 2025-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finances',
            old_name='assets',
            new_name='current_assets',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='cash_cash_equivalents',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='finances',
            name='share_holder_equity',
        ),
        migrations.RemoveField(
            model_name='refvalues',
            name='max',
        ),
        migrations.RemoveField(
            model_name='refvalues',
            name='min',
        ),
        migrations.AddField(
            model_name='refvalues',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refvalues',
            name='sector',
            field=models.CharField(default='Construction, civil engineering, real estate', max_length=255),
        ),
        migrations.AlterField(
            model_name='refvalues',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
