# Generated by Django 5.0.6 on 2025-04-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='frequency',
            field=models.CharField(choices=[('DAYLY', 'DAYLY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('ANNUALY', 'ANNUALY')], default='MONTHLY', max_length=255),
        ),
    ]
