# Generated by Django 5.0.6 on 2025-04-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0003_goals_allocated_amount_goals_last_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitems',
            name='expense_done',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=255),
        ),
    ]
