# Generated by Django 5.0.6 on 2025-04-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0003_expenses_name_goals_name_alter_expenses_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsitems',
            name='domain_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_user_id_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='goalsitems',
            name='expense_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal_expense_id_item', to='PersonalFinance.expenses'),
        ),
    ]
