# Generated by Django 5.0.6 on 2025-04-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0004_alter_expenseitems_expense_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomes',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomes',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
