# Generated by Django 5.0.6 on 2025-04-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0005_remove_expenses_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goals',
            name='name',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goals',
            name='description',
            field=models.TextField(default='dede'),
            preserve_default=False,
        ),
    ]
