# Generated by Django 5.0.6 on 2025-04-15 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0005_incomes_is_locked_incomes_locked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomes',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='incomes',
            name='locked_at',
        ),
    ]
