# Generated by Django 5.0.6 on 2025-04-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0006_remove_goals_name_alter_expenses_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitems',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
