# Generated by Django 5.0.6 on 2025-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalFinance', '0006_remove_incomes_is_locked_remove_incomes_locked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
