# Generated by Django 5.0.6 on 2025-04-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='DataFiles/')),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(blank=True, choices=[('XAF', 'XAF'), ('EUR', 'EUR'), ('USD', 'USD')], default='XAF', max_length=5, null=True)),
                ('data_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_format', models.CharField(blank=True, max_length=50, null=True)),
                ('delete_duplicate', models.BooleanField(default=True)),
                ('merge_existing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
