# Generated by Django 5.0.6 on 2025-03-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingoptions',
            name='processing_options',
            field=models.JSONField(),
        ),
    ]
