# Generated by Django 5.0.6 on 2025-03-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0002_alter_processingoptions_processing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingoptions',
            name='processing_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
