# Generated by Django 5.0.6 on 2025-03-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0003_alter_processingoptions_processing_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingoptions',
            name='processing_options',
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='advanced_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='automatic_categorization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='detect_duplicate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='merge_existing',
            field=models.BooleanField(default=False),
        ),
    ]
