# Generated by Django 5.0.6 on 2025-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0004_remove_processingoptions_processing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
