# Generated by Django 5.0.6 on 2025-03-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0005_datafile_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingoptions',
            name='advanced_validation',
        ),
        migrations.RemoveField(
            model_name='processingoptions',
            name='automatic_categorization',
        ),
    ]
