# Generated by Django 5.0.6 on 2025-03-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0006_remove_processingoptions_advanced_validation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingoptions',
            old_name='detect_duplicate',
            new_name='delete_duplicate',
        ),
    ]
