# Generated by Django 5.0.6 on 2025-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataManagement', '0007_rename_detect_duplicate_processingoptions_delete_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='processed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
